// Train/evaluate Learned-v1 on grouped ranking JSONL generated by dataset:split.
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { evaluateRankingModel, fitRankingModel, modelHash } from './ranking-model.mjs';

const here = fileURLToPath(new URL('.', import.meta.url));
const defaultRuntime = resolve(here, '..', 'runtime');

function parseJsonLines(text) {
  return String(text || '').split(/\r?\n/).filter(Boolean).flatMap(line => { try { return [JSON.parse(line)]; } catch { return []; } });
}

async function loadRows(path) { return parseJsonLines(await readFile(path, 'utf8').catch(() => '')); }
async function sha256(path) { return `sha256:${createHash('sha256').update(await readFile(path).catch(() => '')).digest('hex')}`; }

export async function trainRanking({ splitDir = join(defaultRuntime, 'datasets', 'ranking-split.v1'), modelOutput = join(defaultRuntime, 'models', 'learned-v1.json'), reportOutput = join(defaultRuntime, 'reports', 'learned-v1-sanity.v1.json'), options = {} } = {}) {
  const paths = Object.fromEntries(['train', 'valid', 'test'].map(name => [name, join(splitDir, `${name}.jsonl`)]));
  const sets = { train: await loadRows(paths.train), valid: await loadRows(paths.valid), test: await loadRows(paths.test) };
  const model = fitRankingModel(sets.train, options);
  const metrics = Object.fromEntries(Object.entries(sets).map(([name, rows]) => [name, evaluateRankingModel(model, rows)]));
  const artifact = { ...model, model_hash: modelHash(model), provenance: { split_dir: splitDir, input_sha256: Object.fromEntries(await Promise.all(Object.entries(paths).map(async ([name, path]) => [name, await sha256(path)]))), hidden_information_policy: 'Public candidate features only; private/hidden/identity/card fields are excluded at ingestion.' } };
  const report = { schema_version: 'ranking-sanity-report.v1', generated_at: new Date().toISOString(), status: sets.train.length && sets.valid.length && sets.test.length ? 'candidate' : 'insufficient_evidence', model: { model_id: model.model_id, model_hash: artifact.model_hash, feature_count: model.feature_names.length }, data: Object.fromEntries(Object.entries(sets).map(([name, rows]) => [name, rows.length])), metrics, label_policy: 'Pairwise outcome-weighted behavior: winner chosen > unchosen; loser unchosen > chosen. This is a noisy preference proxy, not a counterfactual truth label.', training_config: model.training, promotion_policy: 'Offline sanity only; online paired gate is required before any champion change.' };
  await mkdir(dirname(modelOutput), { recursive: true });
  await mkdir(dirname(reportOutput), { recursive: true });
  await writeFile(modelOutput, JSON.stringify(artifact, null, 2) + '\n');
  await writeFile(reportOutput, JSON.stringify(report, null, 2) + '\n');
  return { artifact, report };
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) {
  try {
    const runtime = resolve(process.env.XB_RUNTIME_DIR || defaultRuntime);
    const result = await trainRanking({ splitDir: process.env.XB_RANKING_SPLIT_DIR || join(runtime, 'datasets', 'ranking-split.v1'), modelOutput: process.env.XB_RANKING_MODEL_OUT || join(runtime, 'models', 'learned-v1.json'), reportOutput: process.env.XB_RANKING_SANITY_OUT || join(runtime, 'reports', 'learned-v1-sanity.v1.json'), options: { epochs: Number(process.env.XB_RANKING_EPOCHS) || 8, learningRate: Number(process.env.XB_RANKING_LR) || 0.025 } });
    console.log(JSON.stringify({ status: result.report.status, model_hash: result.report.model.model_hash, data: result.report.data, metrics: result.report.metrics }, null, 2));
    if (result.report.status !== 'candidate') process.exitCode = 2;
  } catch (error) {
    console.error(`[train-ranking] ${error.message}`);
    process.exitCode = 1;
  }
}
